// <auto-generated />
using System;
using CopaHAS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CopaHAS.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CopaHAS.Models.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_ESTADIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidade = 78838,
                            Cidade = "Rio de Janeiro",
                            Nome = "Maracanã"
                        },
                        new
                        {
                            Id = 2,
                            Capacidade = 66795,
                            Cidade = "São Paulo",
                            Nome = "Morumbi"
                        },
                        new
                        {
                            Id = 3,
                            Capacidade = 43713,
                            Cidade = "São Paulo",
                            Nome = "Allianz Parque"
                        },
                        new
                        {
                            Id = 4,
                            Capacidade = 49205,
                            Cidade = "São Paulo",
                            Nome = "Arena Corinthians"
                        },
                        new
                        {
                            Id = 5,
                            Capacidade = 61927,
                            Cidade = "Belo Horizonte",
                            Nome = "Mineirão"
                        },
                        new
                        {
                            Id = 6,
                            Capacidade = 55662,
                            Cidade = "Porto Alegre",
                            Nome = "Arena do Grêmio"
                        },
                        new
                        {
                            Id = 7,
                            Capacidade = 50842,
                            Cidade = "Porto Alegre",
                            Nome = "Beira-Rio"
                        });
                });

            modelBuilder.Entity("CopaHAS.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<int>("NumeroCamisa")
                        .HasColumnType("int");

                    b.Property<string>("Posicao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SelecaoId");

                    b.ToTable("TB_JOGADORES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Hugo Souza",
                            NumeroCamisa = 1,
                            Posicao = "Goleiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Yuri Alberto",
                            NumeroCamisa = 9,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Danilo",
                            NumeroCamisa = 2,
                            Posicao = "Lateral Direito",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Marquinhos",
                            NumeroCamisa = 4,
                            Posicao = "Zagueiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Casemiro",
                            NumeroCamisa = 5,
                            Posicao = "Volante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Alex Sandro",
                            NumeroCamisa = 6,
                            Posicao = "Lateral Esquerdo",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Lucas Paquetá",
                            NumeroCamisa = 7,
                            Posicao = "Meio Campo",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Bruno Guimarães",
                            NumeroCamisa = 8,
                            Posicao = "Meio Campo",
                            SelecaoId = 0,
                            Status = 2
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Richarlison",
                            NumeroCamisa = 10,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Vinicius Jr",
                            NumeroCamisa = 11,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Rodrygo",
                            NumeroCamisa = 19,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 3
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Alisson",
                            NumeroCamisa = 23,
                            Posicao = "Goleiro",
                            SelecaoId = 0,
                            Status = 4
                        });
                });

            modelBuilder.Entity("CopaHAS.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstadioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadioId");

                    b.ToTable("TB_JOGOS", (string)null);
                });

            modelBuilder.Entity("CopaHAS.Models.JogoSelecao", b =>
                {
                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("int");

                    b.Property<int>("Gols")
                        .HasColumnType("int");

                    b.Property<int>("GolsDecisaoPenaltis")
                        .HasColumnType("int");

                    b.Property<int>("GolsProrrogacao")
                        .HasColumnType("int");

                    b.HasKey("JogoId", "SelecaoId");

                    b.HasIndex("SelecaoId");

                    b.ToTable("TB_JOGOS_SELECOES", (string)null);
                });

            modelBuilder.Entity("CopaHAS.Models.Selecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_SELECOES", (string)null);
                });

            modelBuilder.Entity("CopaHAS.Models.Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SelecaoId")
                        .IsUnique();

                    b.ToTable("TB_TECNICOS", (string)null);
                });

            modelBuilder.Entity("CopaHAS.Models.Jogador", b =>
                {
                    b.HasOne("CopaHAS.Models.Selecao", "SelecaoIdNavegacao")
                        .WithMany("Jogadores")
                        .HasForeignKey("SelecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SelecaoIdNavegacao");
                });

            modelBuilder.Entity("CopaHAS.Models.Jogo", b =>
                {
                    b.HasOne("CopaHAS.Models.Estadio", "EstadioIdNavegacao")
                        .WithMany("Jogos")
                        .HasForeignKey("EstadioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadioIdNavegacao");
                });

            modelBuilder.Entity("CopaHAS.Models.JogoSelecao", b =>
                {
                    b.HasOne("CopaHAS.Models.Jogo", "JogoIdNavegacao")
                        .WithMany("JogoSelecoes")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CopaHAS.Models.Selecao", "SelecaoIdNavegacao")
                        .WithMany("jogoSelecoes")
                        .HasForeignKey("SelecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JogoIdNavegacao");

                    b.Navigation("SelecaoIdNavegacao");
                });

            modelBuilder.Entity("CopaHAS.Models.Tecnico", b =>
                {
                    b.HasOne("CopaHAS.Models.Selecao", "SelecaoIdNavegacao")
                        .WithOne("Tecnico")
                        .HasForeignKey("CopaHAS.Models.Tecnico", "SelecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SelecaoIdNavegacao");
                });

            modelBuilder.Entity("CopaHAS.Models.Estadio", b =>
                {
                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("CopaHAS.Models.Jogo", b =>
                {
                    b.Navigation("JogoSelecoes");
                });

            modelBuilder.Entity("CopaHAS.Models.Selecao", b =>
                {
                    b.Navigation("Jogadores");

                    b.Navigation("Tecnico");

                    b.Navigation("jogoSelecoes");
                });
#pragma warning restore 612, 618
        }
    }
}
